repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--quiet]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black, --filter-files, --quiet]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.277
    hooks:
      - id: ruff
        args: [--select, T20, --select, E, --ignore, E501, --ignore, E402]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: false
        types_or: [python]
        require_serial: true

default_language_version:
    python: python3.11
