sites:

  yle:
    description: Finnish news site
    active: true
    urls:
      - name: yle_en
        url: "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS"
      - name: yle_rus
        url:  "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NOVOSTI"
      - name: yle_vaasa
        url: "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_UUTISET&concepts=18-148149"
        translate:
          from: "fi"
          to: "en-us"

  dtpptz:
    description: Road incidents in Petrozavodsk
    active: false
    urls:
      - name: dtp_ptz
        url: "https://dtpptz.ru/"

  stolicaonego:
    description: Local news from Petrozavodsk
    active: false
    urls:
      - name: stolica_onego_society
        url: "https://stolicaonego.ru/news/society/"
      - name: stolica_onego_incident
        url: "https://stolicaonego.ru/news/incident/"
      - name: stolica_onego_personal
        url: "https://stolicaonego.ru/news/personal/"

  meduza:
    description: Russian news
    active: true
    urls:
      - name: meduza
        url: "https://meduza.io/rss/news"
  
  novayagazeta:
    description: Russian news
    active: true
    urls:
      - name: novayagazeta_rus
        active: false
        url: "https://novayagazeta.ru/feed/rss"
      - name: novayagazeta_eu
        active: true
        url: "https://novayagazeta.eu/feed/rss"

  radiot:
    description: Tech news from radio-t
    active: true
    urls:
      - name: radio-t
        url: "https://news.radio-t.com/rss"
