version: '3'
services:
    app:
        container_name: ptz_news
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
        build: .
        restart: unless-stopped
        platform: linux/arm/v7
        env_file:
          - .env
        tty: true
        logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"






