[tool.poetry]
name = "news"
version = "0.1.0"
description = ""
authors = ["bobokrut <egor-evlampiev@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
feedparser = "^6.0.10"
loguru = "^0.7.0"
pyyaml = "^6.0"
deepl = "^1.15.0"
openai = "^0.27.8"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"
debugpy = "^1.6.7"
ruff = "^0.0.278"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ["py311"]

[tool.pyright]
typeCheckingMode = "basic"
venvPath = "/home/bobokrut/.cache/pypoetry/virtualenvs"
venv = "news-VBAa4j2y-py3.11"
pythonVersion = "3.11"
useLibraryCodeForTypes = false

[tool.ruff]
select = ["E", "F", "T20"]
ignore = ["E402", "E501"]

