name: CI

on:
  push:
    tags:
      - '*'
jobs:

  code-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Installing poetry
        run: pipx install poetry

      - uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.10.4' 
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use "3.10.4"
          poetry install
          
      - name: mypy
        run: |
          poetry env use "3.10.4"
          poetry run mypy *.py

      - name: black
        run: |
          poetry env use "3.10.4"
          poetry run black --check .


      - name: pytest
        run: |
          poetry env use "3.10.4"
          poetry run pytest **.py || if [ $? -eq 5 ] ; then echo 0; else echo $?; fi

  build:

    needs: code-check
    runs-on: self-hosted

    steps:

      - name: deploying from master 
        run: |
          cd /home/pi/progs/news
          git pull origin master
          docker compose up -d --build

      - name: sleep for 5 sec.
        run: sleep 5

      - name: printing logs from container
        run: docker logs ptz_news

