name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  code-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.4' 
      - run: |
          pip install --upgrade pip
          pip install mypy==v0.942 types-pyyaml==6.0.5 types-requests==2.27.16
          mypy *.py

  build:

    needs: code-check
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cd /home/pi/progs/news
          git pull origin master
          docker compose up -d --build
